MIN_CPU_COUNT: int = 1
MAX_CPU_COUNT: int = 1024

MIN_RAM_SIZE_MB: int = 1024
MAX_RAM_SIZE_MB: int = 65536

MIN_HDD_SIZE_GB: int = 8
MAX_HDD_SIZE_GB: int = 2048

VPS_STATUS_MAX_LENGTH: int = 7

MAX_VALUES_PER_PAGE: int = 25
