# Generated by Django 4.2 on 2025-01-22 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPS",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID сервера",
                    ),
                ),
                (
                    "cpu",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1024),
                        ],
                        verbose_name="Количество процессоров",
                    ),
                ),
                (
                    "ram",
                    models.PositiveSmallIntegerField(
                        default=1024,
                        validators=[
                            django.core.validators.MinValueValidator(1024),
                            django.core.validators.MaxValueValidator(65536),
                        ],
                        verbose_name="Объем оперативной памяти (Мб)",
                    ),
                ),
                (
                    "hdd",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(2048),
                        ],
                        verbose_name="Объем жесткого диска (Гб)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("start", "Started"),
                            ("block", "Blocked"),
                            ("stop", "Stopped"),
                        ],
                        default="start",
                        max_length=5,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPS сервер",
                "verbose_name_plural": "VPS серверы",
                "ordering": ("status",),
            },
        ),
    ]
