# Generated by Django 4.2 on 2025-01-22 09:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps", "0002_alter_vps_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vps",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID сервера",
            ),
        ),
    ]
